### ISSUE TITLE
Issue with password protected room

### ISSUE THREAD

**Issue by Laugslander** [PTS3-S34A/User-Interface#49]
Steps to reproduce the issue:

- Create new password protected room on client 1.
- Join the room on client 2 and enter a wrong password.
- Join the room on client 2 and enter the right password.
- Leave the room on client 2.
- The client 2 user does not leave the session (client 2 user still visible on client 1 and session occupancy is not recuded).

**Comment by Ranray** [comment]
Fixed this issue in Pull request #69 .
